In [ ]:
# the path of image in UAV123 is E:\UAV123\Dataset_UAV123\UAV123\data_seq\UAV123\
# the path of image in OTB100 is E:\OTB100
# the path of image in TrackingNet is E:\

import cv2 
import numpy as np 
import random
import tensorly as tl
from tensorly.decomposition import tucker
from tensorly.decomposition import parafac
from IPython import display

# print(cv2.getBuildInformation())

#import cupy as cp
def count_frames_manual(video):
    total = 0
    while True:
        (grabbed, frame) = video.read()
        if not grabbed:
            break
        total += 1

    return total

sample1 = cv2.VideoCapture('./survelliance/Ch3_20211025102801_2.mp4')
sample2 = cv2.VideoCapture('./survelliance/Ch3_20211025174706_2.mp4')
sample3 = cv2.VideoCapture('./survelliance/Ch3_20211025195110_2.mp4')
sample4 = cv2.VideoCapture('./survelliance/pedestrian-track/Ch3_20211025113444_2.mp4')
test_sample = cv2.VideoCapture('./survelliance/material3.mp4')
grey_sample = cv2.VideoCapture('./survelliance/material4.mp4')
sample1_frames = int(sample1.get(cv2.CAP_PROP_FRAME_COUNT))
print("SAMPLE1 " + str(sample1_frames))
sample2_frames = int(sample2.get(cv2.CAP_PROP_FRAME_COUNT))
print("SAMPLE2 " + str(sample2_frames))
sample3_frames = int(sample3.get(cv2.CAP_PROP_FRAME_COUNT))
sample4_frames = int(sample4.get(cv2.CAP_PROP_FRAME_COUNT))
test_frames = int(test_sample.get(cv2.CAP_PROP_FRAME_COUNT))
print("TEST SAMPLE:" + str(test_frames))
grey_frames = int(grey_sample.get(cv2.CAP_PROP_FRAME_COUNT))


def read_frames(video_capture, max_frames):
    frames_array = []
    frame_nb = 0
    
    while video_capture.isOpened() and frame_nb < max_frames:
        ret, frame = video_capture.read()
        
        frames_array.append(frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        frame_nb += 1
    video_capture.release()
    cv2.destroyAllWindows()
    return frames_array

#x_gpu = cp.ones((100,100,100))
sample_1_array = read_frames(video_capture = sample1, max_frames = sample1_frames)
sample_2_array = read_frames(video_capture = sample2, max_frames = sample2_frames)
test_sample_array = read_frames(video_capture = test_sample , max_frames = test_frames)

In [ ]:
import cv2
import numpy as np
import random
import tensorly as tl
from tensorly.decomposition import tucker, parafac
from IPython import display
#import cupy as cp
import math
import os
import subprocess
import torch
import sys
import datetime

def count_frames_manual(video):
    total = 0
    while True:
        (grabbed, frame) = video.read()
        if not grabbed:
            break
        total += 1

    return total


sample1 = cv2.VideoCapture('./survelliance/Ch3_20211025102801_2.mp4') # person nubmer-4
sample2 = cv2.VideoCapture('./survelliance//Ch3_20211025174706_2.mp4')# person number-4

sample3 = cv2.VideoCapture('./survelliance/Ch3_20211025195110_2.mp4')# person number-8
sample4 = cv2.VideoCapture('./survelliance/Ch3_20211025113444_2.mp4')# person number-4
test_sample = cv2.VideoCapture('./survelliance/material3.mp4')
sample1_frames = int(sample1.get(cv2.CAP_PROP_FRAME_COUNT))
sample2_frames = int(sample2.get(cv2.CAP_PROP_FRAME_COUNT))
print("SAMPLE1 " + str(sample1_frames))
print("SAMPLE2 " + str(sample2_frames))

sample3_frames = int(sample3.get(cv2.CAP_PROP_FRAME_COUNT))
print("SAMPLE3 " + str(sample3_frames))
sample4_frames = int(sample4.get(cv2.CAP_PROP_FRAME_COUNT))
print("SAMPLE4 " + str(sample4_frames))

test_frames = int(test_sample.get(cv2.CAP_PROP_FRAME_COUNT))
print("TEST SAMPLE:" + str(test_frames))

print("TEST SAMPLE:" + str(test_frames))

def read_frames(video_capture, max_frames, batch_size, stop_size):
    batch_list = []
    frame_nb = 0

    for batch_id in range(0, math.ceil(max_frames / batch_size)):
        frames_array = []

        #print(batch_id)
        #print(video_capture.isOpened())
        flag = 1
        # within the array, the frame_nb should be 0-99, 100-199, 200-299 ....
        while video_capture.isOpened() and frame_nb <= batch_size * (batch_id + 1) and flag <= batch_size:
            ret, frame = video_capture.read()
            if not ret:
                break
            frames_array.append(frame)

            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

            frame_nb += 1
            if frame_nb == batch_size * (batch_id + 1):
                break
            flag += 1

        # print(frames_array)
        batch_list.append(frames_array)
        batch_id += 1
        if batch_id == stop_size:
            break;
    video_capture.release()
    cv2.destroyAllWindows()
    return batch_list

count_dynamic = 0
count_dy = []
count_static = 0
count_sta = []

In [ ]:
sample_gray_array = read_frames(video_capture = grey_sample, max_frames = grey_frames, batch_size=50, stop_size=20)
sample_1_array = read_frames(video_capture = sample1, max_frames = sample1_frames, batch_size=100, stop_size=10)
sample_2_array = read_frames(video_capture = sample2, max_frames = sample2_frames, batch_size=100, stop_size=10)
sample_3_array = read_frames(video_capture = sample3, max_frames = sample3_frames, batch_size=100, stop_size=10)
sample_4_array = read_frames(video_capture = sample4, max_frames = sample4_frames, batch_size=100, stop_size=10) 


In [ ]:
'''
a_100 = datetime.datetime.now()
sample_1_array = read_frames(video_capture = sample1, max_frames = sample1_frames, batch_size=100, stop_size=10)
b_100 = datetime.datetime.now()
print("time diff = " + str(b_100 - a_100))


                                                                                                                                 
a_50 = datetime.datetime.now()
sample_1_array_50 = read_frames(video_capture = sample1, max_frames = sample1_frames, batch_size=50, stop_size=20)
b_50 = datetime.datetime.now()
print("time diff = " + str(b_50 - a_50))

a_30 = datetime.datetime.now()
sample_1_array_30 = read_frames(video_capture = sample1, max_frames = sample1_frames, batch_size=33, stop_size=30)
b_30 = datetime.datetime.now()
print("time diff = " + str(b_30 - a_30))


test_sample_array = read_frames(video_capture = test_sample, max_frames = test_frames, batch_size=100, stop_size=10)
a_100_2 = datetime.datetime.now()
sample_2_array = read_frames(video_capture = sample2, max_frames = sample2_frames, batch_size=30, stop_size=33)
b_100_2 = datetime.datetime.now()
print("time diff 2 = " + str(b_100_2 - a_100_2))


a_50_2 = datetime.datetime.now()
sample_2_array_50 = read_frames(video_capture = sample2, max_frames = sample2_frames, batch_size=50, stop_size=20)
b_50_2 = datetime.datetime.now()
print("time diff 2 = " + str(b_50_2 - a_50_2))


a_30_2 = datetime.datetime.now()
sample_2_array_30 = read_frames(video_capture = sample2, max_frames = sample2_frames, batch_size=33, stop_size=30)
b_30_2 = datetime.datetime.now()
print("time diff 2 = " + str(b_30_2 - a_30_2))

a_100_3 = datetime.datetime.now()
sample_3_array = read_frames(video_capture = sample3, max_frames = sample3_frames, batch_size=100, stop_size=10)
b_100_3 = datetime.datetime.now()
print("time diff 3 = " + str(b_100_3 - a_100_3))

a_50_3 = datetime.datetime.now()
sample_3_array_50 = read_frames(video_capture = sample3, max_frames = sample3_frames, batch_size=50, stop_size=20)
b_50_3 = datetime.datetime.now()
print("time diff 3 = " + str(b_50_3 - a_50_3))

a_30_3 = datetime.datetime.now()
sample_3_array_30 = read_frames(video_capture = sample3, max_frames = sample3_frames, batch_size=33, stop_size=30)
b_30_3 = datetime.datetime.now()
print("time diff 3 = " + str(b_30_3 - a_30_3))

a_100_4 = datetime.datetime.now()
sample_4_array = read_frames(video_capture = sample4, max_frames = sample4_frames, batch_size=100, stop_size=10) 
b_100_4 = datetime.datetime.now()
print("time diff 4 = " + str(b_100_4 - a_100_4))

a_75_4 = datetime.datetime.now()
sample_4_array_75 = read_frames(video_capture = sample4, max_frames = sample4_frames, batch_size=75, stop_size=14) 
b_75_4 = datetime.datetime.now()
print("time diff 4 = " + str(b_75_4 - a_75_4))

a_50_4 = datetime.datetime.now()
sample_4_array_50 = read_frames(video_capture = sample4, max_frames = sample4_frames, batch_size=50, stop_size=20) 
b_50_4 = datetime.datetime.now()
print("time diff 4 = " + str(b_50_4 - a_50_4))

a_30_4 = datetime.datetime.now()
sample_4_array_30 = read_frames(video_capture = sample4, max_frames = sample4_frames, batch_size=33, stop_size=30) 
b_30_4 = datetime.datetime.now()
print("time diff 4 = " + str(b_30_4 - a_30_4))



print(len(test_sample_array))
'''

In [ ]:
for i in range(len(sample_1_array[0])):
    for j in range(len(sample_1_array[0][i])):
        for k in range(len(sample_1_array[0][i][j])):
            sparsity_array_val = sample_1_array[0][i][j][k]
            #print(sparsity_array_val)
            if(sparsity_array_val[0] > 10):
                count_dynamic += 1
            else:
                count_static += 1


print(count_dynamic)
print(count_static)

In [ ]:
import tensorly as tl

grey_tensor = tl.tensor(np.array(sample_gray_array))
tensor_test = tl.tensor(np.array(test_sample_array))
tensor_1 = tl.tensor(np.array(sample_1_array))
tensor_2 = tl.tensor(np.array(sample_2_array))

tensor_3 = tl.tensor(np.array(sample_3_array))
tensor_4 = tl.tensor(np.array(sample_4_array))


random.seed(1)
random_frames = random.sample(range(0, 30), 10)
print(random_frames)

fixed_frames = range(0,16)

print(tensor_1.shape)


'''

Euclidean_distance_1 = np.linalg.norm(core_subset_sample1 - core_subset_sample2)
Euclidean_distance_2 = np.linalg.norm(core_subset_sample1 - core_subset_sample3)

Euclidean_distance_3 = np.linalg.norm(core_subset_sample2 - core_subset_sample3)
Euclidean_distance_4 = np.linalg.norm(core_subset_sample1 - core_subset_sample4)
Euclidean_distance_5 = np.linalg.norm(core_subset_sample2 - core_subset_test)

np.set_printoptions(threshold=sys.maxsize)


print(Euclidean_distance_1) 
print(Euclidean_distance_2) 
print(Euclidean_distance_3)
print(Euclidean_distance_4)
print(Euclidean_distance_5)
print(factors_subset_sample1)
print(factors_subset_sample2)


with open('output_1.txt', 'a') as f1:
    print(factors_subset_sample1, file=f1)


with open('output_2.txt', 'a') as f2:
    print(factors_subset_sample2, file=f2)
    
print(factors_subset_sample3)
print(factors_subset_sample4)
'''

In [ ]:
'''
subset_sample1_cp = tensor_1[fixed_frames,: ,: ,:].astype('d')
subset_sample2_cp = tensor_2[fixed_frames,: ,: ,:].astype('d')

subset_sample_test = tensor_test[random_frames,: ,: ,:].astype('d')

subset_sample1 = tensor_1[random_frames,: ,: ,:].astype('d')
subset_sample2 = tensor_2[random_frames,: ,: ,:].astype('d')


subset_sample3 = tensor_3[random_frames,: ,: ,:].astype('d')
subset_sample4 = tensor_4[random_frames,: ,: ,:].astype('d')



core_subset_test, factors_subset_test = tucker(subset_sample_test, rank = [1,1,1,1])
core_subset_sample1, factors_subset_sample1 = tucker(subset_sample1, rank = [1,1,1,1])
core_subset_sample2, factors_subset_sample2 = tucker(subset_sample2, rank = [1,1,1,1])

core_subset_sample1_4 = tucker(subset_sample1, rank = [2,2,2,2])
core_subset_sample3, factors_subset_sample3 = tucker(subset_sample3, rank = [1,1,1,1])
core_subset_sample4, factors_subset_sample4 = tucker(subset_sample4, rank = [1,1,1,1])

from tensorly.decomposition import parafac

#cp decomposition for foreground and background
#separate into low-rank tensor and sparse-tensor
core_subset_sample1_cp = parafac(subset_sample1_cp, rank=3 ,n_iter_max=50, tol = 1.0e-5, linesearch=False)
core_subset_sample2_cp = parafac(subset_sample2_cp, rank=3 ,n_iter_max=50, tol = 1.0e-5, linesearch=False)
'''

In [446]:
def conv_diagnal(singular_value, rank):
    s_diag = np.zeros((rank, rank))
    for i in range(0, rank):
        for j in range(0, rank):
                if i == j:
                    s_diag[i][j] = singular_value[i]
    return s_diag           

In [690]:
#algorithm goes here 
import numpy as np 
import matplotlib 
import matplotlib.pyplot as plt 
from timeit import timeit
from PIL import Image
# from skimage import color,io
import scipy
from sklearn.decomposition import TruncatedSVD
import random
import cv2
import torch
import torchvision.transforms.functional as fn
#from plotter import convergence_plot, kwargs, setup_layout

def sp_noise(image,prob):
    '''
    Add salt and pepper noise to image
    prob: Probability of the noise
    '''
    output = np.zeros(image.shape,np.uint8)
    thres = 1 - prob 
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            rdn = random.random()
            if rdn < prob:
                output[i][j] = 0
            elif rdn > thres:
                output[i][j] = 255
            else:
                output[i][j] = image[i][j]
    return output


def convert_RGB(input_img):
    if input_img.ndim == 2 or (input_img.ndim==3 and input_img.shape[2] ==1):
        # your image is in grayscale
        input_img = color.gray2rgb(input_img)
    elif input_img.ndim==3 and input_img.shape[2] == 4:
        # your image is in RGBA
        input_img = color.rgba2rgb(input_img)
    else:
        # your image is already in RGB
        assert input_img.ndim == 3 and input_img.shape[2] == 3
    return input_img

In [773]:
from skimage import color, io
import cv2

img = io.imread('./survelliance/0034.jpg')
img_res = convert_RGB(img)
print(img.shape)

#input
imgGray = color.rgb2gray(img_res)
print(imgGray*255)
img_tensor = fn.to_tensor(img_res).reshape(img.shape[0], img.shape[1], 3)
noise_img = sp_noise(img, 0.1)
print("test: " + str(noise_img.shape))
cv2.imwrite('./res/sp_noise.jpg', noise_img)
gray_noise = cv2.cvtColor(noise_img, cv2.COLOR_BGR2GRAY)
cv2.imwrite('./res/sp_noise_gray.jpg', gray_noise)
# normalize_img = fn.normalize(torch.tensor(noise_img), mean=[0.5000], std=[.1000])


n1 = min(imgGray.shape[0], imgGray.shape[1])
n2 = max(imgGray.shape[0], imgGray.shape[1])
rank = k = 3
def svd_res(A, rank):
    print(A.shape)
    u, sigma, v = scipy.sparse.linalg.svds(A, k=rank)
    return u, sigma, v

def nuclear_norm(A):
    res_norm = np.linalg.norm(A, ord='nuc',keepdims=True)
    return res_norm

left, singular, right = svd_res(color.rgb2gray(noise_img)*255, 30)

S_sparse = color.rgb2gray(noise_img)*255 - np.matmul(left , right)

#nuclear_norm = nuclear_norm(imgGray)

#the rank r must less than 1080
L0 = np.zeros((img.shape[0], img.shape[1]))

# 1080 * 5 
# 1920 * 1
# singular_diagnal 
singular_diagnal = conv_diagnal(singular, 30)

for i in range(0, 30):
    print(i)
    print('===============')
    print(L0)
    print('===============')
    print(singular_diagnal[i].shape)
    print(left[i].shape)
    print(right[i].shape)
    L0 += np.dot(np.matmul(singular_diagnal[i], left[i]), right[i])

print("==========")
print(L0)

im_output_low_rank = Image.fromarray(L0)
if im_output_low_rank.mode == "F":
    im_output_low_rank = im_output_low_rank.convert('RGB')
im_output_low_rank.save("./res/output_low_img_L0.png")

(576, 768, 3)
[[0.00000e+00 1.00000e+01 1.40000e+01 ... 2.55000e+02 2.55000e+02
  2.55000e+02]
 [8.00000e+00 1.90000e+01 2.40000e+01 ... 2.55000e+02 2.55000e+02
  2.55000e+02]
 [2.50000e+01 2.40000e+01 2.00000e+01 ... 2.55000e+02 2.55000e+02
  2.55000e+02]
 ...
 [3.09241e+01 3.09241e+01 3.09241e+01 ... 5.61442e+01 5.60000e+01
  5.60000e+01]
 [1.77790e+00 1.77790e+00 1.77790e+00 ... 1.44200e-01 0.00000e+00
  0.00000e+00]
 [6.37500e-01 6.37500e-01 6.37500e-01 ... 1.44200e-01 0.00000e+00
  0.00000e+00]]
test: (576, 768, 3)
(576, 768)
0
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(30,)
(30,)
(768,)
1
[[ 1.60211893 -2.63082199  2.24200783 ...  2.86216644  4.838117
   0.81170875]
 [ 1.60211893 -2.63082199  2.24200783 ...  2.86216644  4.838117
   0.81170875]
 [ 1.60211893 -2.63082199  2.24200783 ...  2.86216644  4.838117
   0.81170875]
 ...
 [ 1.60211893 -2.63082199  2.24200783 ... 

In [774]:
4 * np.linalg.norm(imgGray, keepdims=True)

array([[1568.64101679]])

In [775]:
from skimage import io, color
import os

img2 = io.imread('./survelliance/0034.jpg')
img_res_2 = convert_RGB(img2)
print(img2.shape)

(576, 768, 3)


In [85]:
import numpy
import math
import io
from skimage import color

def svd_res(A, rank):
    u, sigma, v = scipy.sparse.linalg.svds(A, k=rank)
    return u, sigma, v

def nuclear_norm(A):
    res_norm = np.linalg.norm(A, ord='nuc',keepdims=True)
    return res_norm


def singular_threshold(x, tau):
    u, d, vh = np.linalg.svd(x, full_matrices = False)
    res = np.matmul(u * soft_threshold(d, tau),vh)
    return res 


# this method is to calculate the shrinkage operator
def soft_threshold(x, tau):
    para1 = np.sign(x)
    para2 = np.max((np.fabs(x)-tau), 0)
    return np.multiply(para1, para2)


left, singular, right = svd_res(color.rgb2gray(noise_img)*255, 6)

S_sparse = color.rgb2gray(noise_img)*255 - np.matmul(left , right)

nuclear_norm = nuclear_norm(imgGray)

#the rank r must less than 1080
L0 = np.zeros((img.shape[0], img.shape[1]))

singular_diagnal = conv_diagnal(singular, 5)
print(singular_diagnal)

#@ RPCA for decomposition M = L0 + S0
#the nuclear norm in numpy: numpy.linalg.norm
#the L1 norm in numpy 
#the L0 norm in numpy 
#the SVD in tensorflow is memory so the SVD function need to be rewrote 
#L0 could be calculated by SVD where L0 = UDV^T


import numpy as np 
from sklearn.decomposition import TruncatedSVD
import tensorflow as tf

#original video image is m 
def reshape_ori(m):
    m = m.reshape(img.shape[0], img.shape[1], 1)
    m1 = m.reshape(shape_ori[0]*shape_ori[1], shape_ori[2])
    m2 = m.reshape(shape_ori[0], shape_ori[1]*shape_ori[2])
    m3 = m.reshape(shape_ori[2], shape_ori[0]*shape_ori[1])
    shape_ori = m.shape
    return shape_ori

shape1 = img.shape[0] #1080
shape2 = img.shape[1] #1920
shape3 = 1 
shape_0 = (img.shape[0], img.shape[1]) 
n_1 = max(shape1, shape2)
n_2 = min(shape1, shape2)
lam = 3/np.sqrt(n_1)
m = 0.3 * n_1 * n_2
mu = (shape1*shape2)/(3 * np.linalg.norm(img_res, keepdims=True))


# the algorithm start from L0, S0 and Y0
# the shape of M must be n1 * n2
# what does thre do in the algorithm?
def rpca(X):

    # initialization with Lamda(1/squa(n1) where  n_1=max(n1,n2), n_2=min(n1,n2)), Mu, Delta
    # the following steps are converting M to L,S 
    # the probability of reconstructing M which is 1− CN^(−10)

    print(mu)
    # iteration number 
    k=0.1 * n_1 * n_1
    k_test = 10
    #both are positive numeric
    # r is the rank defined of input matrix (1080*1920) 
    
    #rank of L0 
    #L0_rank <= rho_r * n_2 * 1/mu * (np.log(n_1))**(-2)
    r = 1 * n_1/mu
    print(r)
    # rho_r is pending
    rho_r = 1
    rho_s = (n_2 * r) ** (-0.5)
    
    # when the termination is satisfied, iteration could stop 
    # initialization S=0, Y=0, mu>0
    terminate_flag = False
    shape_0 = (X.shape[0], X.shape[1])
    
    # original matrix is M 
    # Low-rank matrix
    L = im_output_low_rank
    # Sparse matrix 
    S = np.zeros(shape_0)
    # Lagrange multiplier matrix 
    Y = np.zeros(shape_0)
    # M is the original tensor 
    count = 0
    iter_num = 0
    # the stop critieria need to be considered 
    while iter_num < 2: #condition required 
        iter_num += 1
        print("iteration number: " + str(iter_num))
        L = singular_threshold(X - S - Y/mu, mu) # result should multiply 255
        S = soft_threshold(X - L + Y/mu, lam * mu) # result should plus 255
        Y = Y + mu * (X - L - S)
        print(torch.tensor(X-L-S).shape)
        '''
        m_tensor = tf.convert_to_tensor(np.array(M),dtype=tf.float32)
        l_tensor = tf.convert_to_tensor(np.array(L),dtype=tf.float32)
        s_tensor = tf.convert_to_tensor(np.array(S),dtype=tf.float32)
        '''
        terminate_flag = False
        terminate_flag = np.linalg.norm((X-L-S).reshape(shape_0[0], shape_0[1]),ord='fro',keepdims=True) <= 10 ** (-6) * np.linalg.norm(X,ord='fro',keepdims=True)
        print(terminate_flag)
        if terminate_flag == True:
            print(iter_num)
            break
    
    return L, S


im_output_low_rank = Image.fromarray(S_sparse)
if im_output_low_rank.mode == "F":
    im_output_low_rank = im_output_low_rank.convert('RGB')
im_output_low_rank.save("./res/output_low_img_S.png")

# preferred with original image plus 255
L_soft = soft_threshold(gray_noise, mu)
print(L_soft)
im_output_low_rank = Image.fromarray(L_soft)
if im_output_low_rank.mode != 'RGB':
    im_output_low = im_output_low_rank.convert('RGB')
im_output_low.save("./res/output_low_img_soft.png")

# preferred with multiply 255
L_res = singular_threshold(gray_noise, lam*mu)
im_output_low_rank = Image.fromarray(L_res)
if im_output_low_rank.mode != 'RGB':
    im_output_low = im_output_low_rank.convert('RGB')
im_output_low.save("./res/output_low_img_singular.png")

[[ 4480.45782149     0.             0.             0.
      0.        ]
 [    0.          4815.86557245     0.             0.
      0.        ]
 [    0.             0.          5326.30820844     0.
      0.        ]
 [    0.             0.             0.          7674.54492286
      0.        ]
 [    0.             0.             0.             0.
  11127.4775511 ]]
[[-0.00000000e+00 -0.00000000e+00  1.31414593e+01 ...  2.54141459e+02
   2.54141459e+02  2.54141459e+02]
 [ 7.14145926e+00  1.81414593e+01  2.31414593e+01 ...  2.54141459e+02
   2.54141459e+02  2.54141459e+02]
 [ 2.41414593e+01  2.31414593e+01  1.91414593e+01 ...  2.54141459e+02
   2.54141459e+02  2.54141459e+02]
 ...
 [ 2.91414593e+01 -0.00000000e+00  2.54141459e+02 ...  5.61414593e+01
   5.51414593e+01  5.51414593e+01]
 [ 1.41459262e-01 -0.00000000e+00  1.41459262e-01 ...  1.41459262e-01
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00  2.54141459e+02 ...  1.41459262e-01
  -0.00000000e+00 -0.00000000e+

In [777]:
print(imgGray.shape)
print(fn.to_tensor(img_res_3))

(576, 768)
tensor([[[0.0000, 0.0392, 0.0549,  ..., 1.0000, 1.0000, 1.0000],
         [0.0314, 0.0745, 0.0941,  ..., 1.0000, 1.0000, 1.0000],
         [0.0980, 0.0941, 0.0784,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [0.1255, 0.1255, 0.1255,  ..., 0.2196, 0.2196, 0.2196],
         [0.0196, 0.0196, 0.0196,  ..., 0.0000, 0.0000, 0.0000],
         [0.0118, 0.0118, 0.0118,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0392, 0.0549,  ..., 1.0000, 1.0000, 1.0000],
         [0.0314, 0.0745, 0.0941,  ..., 1.0000, 1.0000, 1.0000],
         [0.0980, 0.0941, 0.0784,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [0.1216, 0.1216, 0.1216,  ..., 0.2196, 0.2196, 0.2196],
         [0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0392, 0.0549,  ..., 1.0000, 1.0000, 1.0000],
         [0.0314, 0.0745, 0.0941,  ..., 1.0000, 1.0000, 1.0000],
         [0.0980, 0.0941, 0.0784,  ..., 1.0000,

In [778]:
#input
import torch 
from skimage import io, color

img3 = io.imread('./survelliance/0034.jpg')
print(img3.shape)
img_res_3 = convert_RGB(img3)
tensor_3 = torch.tensor(img_res_3)
imgGray = color.rgb2gray(tensor_3)
img_tensor = fn.to_tensor(img_res_3).reshape(img3.shape[0], img3.shape[1],3)

(576, 768, 3)


In [86]:
import math
from skimage import io

shape1 = 240 #1080
shape2 = 320 #1920
shape3 = 1 
shape_0 = (240, 320)    
n_1 = max(shape1, shape2)
n_2 = min(shape1, shape2)
lam = 1/np.sqrt(n_1)
m = 0.1 * n_1 * n_2
mu = (shape1*shape2)/(4 * np.linalg.norm(imgGray[0], 1, keepdims=True))

gamma = 0.05
beta = 1.618
rho = 0.01
k = 0.01 * n_1 * n_1
lam_bda = 10

img = io.imread('./survelliance/0034.jpg')
img_res = convert_RGB(img)
print(img.shape)

#input
imgGray = color.rgb2gray(img_res)
print(imgGray*255)
shape1 = imgGray.shape[0]
shape2 = imgGray.shape[1]

D = imgGray
S_sparse = np.zeros((shape1, shape2))#


t = np.zeros((shape1, shape2))
D = imgGray
# k is the iteration number
rho_k = rho * k

pi = np.zeros((shape1, shape2))
S  = np.zeros((shape1, shape2))


# Lagrangian multiplier
# size of pi is m*n
# hereby S is representing sparse error data  which is basing on the decomposition result
# S is the sparse matrix 
def lagrangian_mul(U, V, S, pi, rho, iter_num, rank):
        pi = D * rho * (iter_num-1)
        # original paper has a differente version with this one 
        # lagrangian = nuclear_norm(low_rank) + lam_bda * numpy.linalg.norm(sparse_tensor, ord=1) + np.inner(pi, D -  np.matmul(U, V) - S) + mu/2 * numpy.linalg.norm(D - np.matmul(U, V)-sparse,ord='fro', keepdims=True) ** 2
        res_1 = np.linalg.norm(S, ord=1) 
        res_2 = lam_bda * subgradient(V, rank, gamma)  
        res_3 = np.inner(D * rho * (iter_num-1), D - np.matmul(U, V) - S)
        res_4 = rho/2 * np.linalg.norm(D -  np.matmul(U, V) - S, ord='fro')**2
        return res_1 + res_2 ,res_3 + res_4
         
# u is constant to get next u 
# u is 1080 * r, vofT is r * 1920
# T and S are 1080*1920

# update steps for u
def orthogonal_proc(v, s, iter_num, rank_of_orth):
    pi = D * rho * (iter_num-1)
    t = D + pi/rho_k
    if v.shape == (shape2, 5):
        pass
    else:
        v = np.transpose(v)  
    left, singular, right = svd_res(np.matmul(t-s, v), rank_of_orth)
    return np.matmul(left, right)


def solve_u(u_input, v, s):
    t = D + pi/rho_k
    u = u_input
    u = rho_k/2 * numpy.linalg.norm(np.matmul(u, v)-(t-s), ord="fro") ** 2
    return u


# update for v
# gamma is larger than 0 
def subgradient(v, rank, gamma):
    singular_proc = []
    left, singular, right = svd_res(v, rank)
    for i in singular:
        each_sin = math.exp(-i/gamma)/gamma 
        singular_proc.append(each_sin)
    diag_ma = conv_diagnal(singular_proc, rank)
    return np.matmul(np.matmul(left, diag_ma), right)

def control_ratio(v,gamma):
    sum = 0
    singular_value = scipy.linalg.svdvals(v)
    num = len(singular_value)
    for i in range(0, num):
        sum += (1-math.exp(-singular_value[i]/gamma))
    return sum

# v is a constant 
# return updated v
def solve_v(v_input, u, s):
    v = v_input
    v_new = control_ratio(v, gamma) + (rho_k/2*lam)*numpy.linalg.norm(np.transpose(v) - np.matmul(np.transpose(t - s), u), ord="fro") ** 2
    return v_new

def optimal_res_v(v_input, sparse_input, u_updated):
    t = D + pi/rho_k 
    v_1 = np.matmul(np.transpose(t-sparse_input),u_updated)  
    v_2 = lam_bda * subgradient(v_input, 3, gamma)/rho_k
    if v_2.shape == (shape2, 5):
        pass
    else:
        v_2 = np.transpose(v_2)  
    v_updated = v_1 - v_2
    return v_updated
    

# update steps for S
def shrinkage_thre(u, v):
    t = D + pi/rho_k
    W= t - numpy.matmul(u,np.transpose(v))
    update_S = np.zeros((t.shape[0], t.shape[1]))
    for i in range(0, len(W)):
        for j in range(0, len(W[0])):
            res = max(abs(numpy.matrix.max(np.matrix(W[i][j]))) - 1/rho_k, 0) * numpy.sign(W[i][j])
            update_S[i][j] = res
    return update_S

# s is a constant 
def solve_s(sparse_input, u, v):
    s = sparse_input
    s_new = numpy.linalg.norm(s, ord=1) + rho_k/2 * numpy.linalg.norm(s-(t-np.matmul(u,v)),ord="fro") ** 2
    return s_new

(576, 768, 3)
[[0.00000e+00 1.00000e+01 1.40000e+01 ... 2.55000e+02 2.55000e+02
  2.55000e+02]
 [8.00000e+00 1.90000e+01 2.40000e+01 ... 2.55000e+02 2.55000e+02
  2.55000e+02]
 [2.50000e+01 2.40000e+01 2.00000e+01 ... 2.55000e+02 2.55000e+02
  2.55000e+02]
 ...
 [3.09241e+01 3.09241e+01 3.09241e+01 ... 5.61442e+01 5.60000e+01
  5.60000e+01]
 [1.77790e+00 1.77790e+00 1.77790e+00 ... 1.44200e-01 0.00000e+00
  0.00000e+00]
 [6.37500e-01 6.37500e-01 6.37500e-01 ... 1.44200e-01 0.00000e+00
  0.00000e+00]]


In [89]:
def visualization(image_input):
    print(img.shape)
    im_output_low_rank = Image.fromarray((image_input.reshape((gray_noise.shape[0], gray_noise.shape[1]))).astype(np.uint8))
    if im_output_low_rank.mode != 'RGB':
        im_output_low = im_output_low_rank.convert('RGB')
    im_output_low.save("./res/output_lang_img_rpca_0034_try.png")

L_rpca, S_rpca = rpca(gray_noise)

print(L_rpca)
print(S_rpca/255)


[44.07324637]
[7.26064056]
iteration number: 1
torch.Size([576, 768])
[[False]]
iteration number: 2
torch.Size([576, 768])
[[False]]
[[-3195.29514488 -4128.34407317 -1975.67588548 ...  2131.84824355
    408.1284199   1266.63895007]
 [-4438.54518135 -1278.23729436 -4800.45639374 ...   824.67449453
   2627.80331401  1020.95467098]
 [-1727.47288811 -4213.30611944 -3117.00549579 ...   625.09337794
   1501.90635307  3615.82002994]
 ...
 [ 1274.94802017 -4175.90017155  9450.80595001 ...  -431.1236115
   1047.06404917  -893.77518617]
 [  679.37991018   252.99955013  -844.05226245 ...  -272.89322772
  -1063.60586962  -365.45544611]
 [ -614.55994364 -1985.79218249  8744.46378523 ...  -522.43878996
  -2038.24637899   962.59032024]]
[[-46.64346788 -47.0922167  -48.22449764 ...  48.88834927  44.67604543
   47.36497361]
 [-46.64346788 -47.0922167  -48.22449764 ...  48.88834927  44.67604543
   47.36497361]
 [-46.64346788 -47.0922167  -48.22449764 ...  48.88834927  44.67604543
   47.36497361]
 ...
 [

In [88]:
S_rpca/(255)

array([[-46.64346788, -47.0922167 , -48.22449764, ...,  48.88834927,
         44.67604543,  47.36497361],
       [-46.64346788, -47.0922167 , -48.22449764, ...,  48.88834927,
         44.67604543,  47.36497361],
       [-46.64346788, -47.0922167 , -48.22449764, ...,  48.88834927,
         44.67604543,  47.36497361],
       ...,
       [ 46.64346788, -47.0922167 , -48.22449764, ..., -48.88834927,
         44.67604543, -47.36497361],
       [ 46.64346788,  47.0922167 , -48.22449764, ..., -48.88834927,
        -44.67604543, -47.36497361],
       [-46.64346788, -47.0922167 , -48.22449764, ..., -48.88834927,
        -44.67604543,  47.36497361]])

In [91]:
visualization(gray_noise - L_rpca/(255))

(576, 768, 3)


In [659]:
gray_noise = gray_noise.astype(np.float32)

In [ ]:
imgGray.shape

In [728]:
# t is changed with interation number
# pi is matching with the original Y 
# input_img is a fixed input frame of video segments

U_input, S_input, V_input = svd_res(imgGray, 5)

# the size of u is always 1080 * rank, singular is rank * rank diagnal
# , v is 1920 * rank, result is vofT

def ALM_directing(left_input, sparse_input, right_input):
    k = 50
    u_0 = U_input
    v_0 = V_input
    s_0 = sparse_input
    for i in range(0, k):
        print("this is the " + str(i) +" iteration.....")
        rho_k = k * rho
        pi = rho_k * D

        # lagrangian_mul(left_input, right_input, sparse_input, pi, rho, k, 3)
        rho_max = float('inf')
        #u_next = solve_u(u_0, right_input, sparse_input) # use V_k and S_k to get U_k+1
        u_next = orthogonal_proc(v_0, s_0, i, 3)
        u_0 = u_next
        #v_next = solve_v(v_0, left_input, sparse_input) # use U_k and S_k to get V_k+1
        v_next = optimal_res_v(v_0, s_0, u_0)
        v_0 = v_next
        print("======v shape in iteration======" + str(v_0.shape))
        #s_next = `solve_s(s_0, left_input, right_input) # use U_k and V_k to get S_k+1
        s_next = shrinkage_thre(u_0, v_0)
        s_0 = s_next
        pi += rho_k * (D - numpy.matmul(left_input, np.transpose(right_input))-sparse_input)
        rho_k = min(beta * rho_k, rho_max)
    print("final" + str(u_0.shape))
    print("final" + str(v_0.shape))
    return numpy.matmul(u_0, np.transpose(v_0))
    
generate_L = ALM_directing(U_input, S, np.transpose(V_input))
im_output_sparse = Image.fromarray(generate_L*255)
if im_output_sparse.mode != 'RGB':
    im_output_rank = im_output_sparse.convert('RGB')
im_output_rank.save("./res/ADMM_res.png")

###### MFRPCA 
# worked!
# Lagrangian Multiplier 
# inputs are U, V, S(result of SVD), pi and rho 
# the input_matrix is M 
def i_largest_singular(input_matrix,i):
    U,S,V = np.linalg.svd(input_matrix)
    i_largest = S.tolist()[i]
    return i_largest

# Lagrangian l and s represents the low rank and sparse matrix 
def lagrangian_aug(l, s): 
    #this step is processing both low rank and sparse 
    #we could input original as well 
    rho_k = rho * k 
    rho = min(beta * rho_k, rho)
    log_ran, spar = log_determinant(l, s)
    return numpy.linalg.norm(log_ran, ord="1") + lam_bda * numpy.linalg.norm(spar,ord=2) + rho/2 * numpy.linalg.norm(imgGray-l-s, ord='fro')^2

# optimization steps of RPCA
# k is depending on the how many iteration will terminate the converge 

import math
import numpy as np 

k=0.05*n_1 * n_1
rho = 0.01
rho = rho * k # k is the iteration number starting from 1
theta = 0 
X = imgGray
# theta = theta + rho * (tf.convert_to_tensor(np.array(X)) - L_res - S_res)
beta = 1.618

########optimization process in log-based RPCA 

# what is diag in for xi? 
# d is the input image
def optimization_process(d, ith, t):
    p,s,q =  scipy.sparse.linalg.svds(d*255, 10)
    print(p.shape)
    res_opt = None
    # ith largest singular value of d
    xi = 0
    t = 1/rho
   # xi = #
    xi = (sorted(s.tolist())[ith] -1)/2 + np.sqrt(abs((1+sorted(s.tolist())[ith])**2/4-t))
    res_opt = np.matmul(p * xi, q)
    
    return res_opt


##### operands could not be broadcast together with shapes
# the x and y represents the L-low rank matrix and S-sparse matrix with original video frame 
def log_determinant(x, y):
    x_a, x_b = x.shape
    I = np.zeros((x_a, x_a))
    for i in range(0, x_a):
        for j in range(0, x_a):
            if i == j: 
                I[i][j] = 1
    #h(L)
    log_rank = np.linalg.slogdet(I + np.matmul(x , np.transpose(x))**0.5)
    
    #C(S)
    y_a, y_b = y.shape
    res_sparsity = 0.0
    for col in range(y_b): 
        #print(y[:, col])
        res_sparsity +=  numpy.log(float(1) + np.linalg.norm(y[:, col], ord=2))
    
    return log_rank, res_sparsity

#pi_next = pi + rho(D - U_input *  np.transpose(V_input) - S_input)
#rho_next = min(beta * rho , rho_max)


this is the 0 iteration.....
======v shape in iteration======(768, 5)
this is the 1 iteration.....
======v shape in iteration======(768, 5)
this is the 2 iteration.....
======v shape in iteration======(768, 5)
this is the 3 iteration.....
======v shape in iteration======(768, 5)
this is the 4 iteration.....
======v shape in iteration======(768, 5)
this is the 5 iteration.....
======v shape in iteration======(768, 5)
this is the 6 iteration.....
======v shape in iteration======(768, 5)
this is the 7 iteration.....
======v shape in iteration======(768, 5)
this is the 8 iteration.....
======v shape in iteration======(768, 5)
this is the 9 iteration.....
======v shape in iteration======(768, 5)
this is the 10 iteration.....
======v shape in iteration======(768, 5)
this is the 11 iteration.....
======v shape in iteration======(768, 5)
this is the 12 iteration.....
======v shape in iteration======(768, 5)
this is the 13 iteration.....
======v shape in iteration======(768, 5)
this is the 14 i

In [732]:
im_output_sparse = Image.fromarray(generate_L*255)
if im_output_sparse.mode != 'RGB':
    im_output_rank = im_output_sparse.convert('RGB')
im_output_rank.save("./res/ADMM_res.png")

In [733]:
print(S_rpca.shape)
log, sparse = log_determinant(L_rpca, S_rpca)
i_largest_singular(X,1)

control_ratio(V_input, gamma)
res_1, res_2 = lagrangian_mul(U_input, V_input, S, D ,rho, 4, 2)
res_opt = optimization_process(X, 4, 1/rho)


(576, 768)


/home/T3090U4/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:105: RuntimeWarning: invalid value encountered in sqrt
/home/T3090U4/.local/lib/python3.7/site-packages/numpy/linalg/linalg.py:2098: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)


(576, 10)


In [734]:
def visualization_ADMM(image_input):
    print(img.shape)
    im_output_low_rank = Image.fromarray((image_input.reshape((gray_noise.shape[0], gray_noise.shape[1]))).astype(np.uint8))
    if im_output_low_rank.mode != 'RGB':
        im_output_low = im_output_low_rank.convert('RGB')
    im_output_low.save("./res/output_lang_img_rpca_ADMM.png")

In [735]:
visualization_ADMM(np.array(res_opt + 255))

(576, 768, 3)
